package pl.kilometrowka.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import pl.kilometrowka.dao.StawkiKierowcyDao;
import pl.kilometrowka.dao.ProfilDao;
import pl.kilometrowka.dao.TydzienDao;
import pl.kilometrowka.dao.StawkiPasazeraDao;
import pl.kilometrowka.dao.DzienDao;
import pl.kilometrowka.dao.TrasaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        StawkiKierowcyDao.createTable(db, ifNotExists);
        ProfilDao.createTable(db, ifNotExists);
        TydzienDao.createTable(db, ifNotExists);
        StawkiPasazeraDao.createTable(db, ifNotExists);
        DzienDao.createTable(db, ifNotExists);
        TrasaDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        StawkiKierowcyDao.dropTable(db, ifExists);
        ProfilDao.dropTable(db, ifExists);
        TydzienDao.dropTable(db, ifExists);
        StawkiPasazeraDao.dropTable(db, ifExists);
        DzienDao.dropTable(db, ifExists);
        TrasaDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(StawkiKierowcyDao.class);
        registerDaoClass(ProfilDao.class);
        registerDaoClass(TydzienDao.class);
        registerDaoClass(StawkiPasazeraDao.class);
        registerDaoClass(DzienDao.class);
        registerDaoClass(TrasaDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
