package pl.kilometrowka.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pl.kilometrowka.dao.StawkiKierowcy;
import pl.kilometrowka.dao.StawkiPasazera;
import pl.kilometrowka.dao.Trasa;

import pl.kilometrowka.dao.StawkiKierowcyDao;
import pl.kilometrowka.dao.StawkiPasazeraDao;
import pl.kilometrowka.dao.TrasaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stawkiKierowcyDaoConfig;
    private final DaoConfig stawkiPasazeraDaoConfig;
    private final DaoConfig trasaDaoConfig;

    private final StawkiKierowcyDao stawkiKierowcyDao;
    private final StawkiPasazeraDao stawkiPasazeraDao;
    private final TrasaDao trasaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stawkiKierowcyDaoConfig = daoConfigMap.get(StawkiKierowcyDao.class).clone();
        stawkiKierowcyDaoConfig.initIdentityScope(type);

        stawkiPasazeraDaoConfig = daoConfigMap.get(StawkiPasazeraDao.class).clone();
        stawkiPasazeraDaoConfig.initIdentityScope(type);

        trasaDaoConfig = daoConfigMap.get(TrasaDao.class).clone();
        trasaDaoConfig.initIdentityScope(type);

        stawkiKierowcyDao = new StawkiKierowcyDao(stawkiKierowcyDaoConfig, this);
        stawkiPasazeraDao = new StawkiPasazeraDao(stawkiPasazeraDaoConfig, this);
        trasaDao = new TrasaDao(trasaDaoConfig, this);

        registerDao(StawkiKierowcy.class, stawkiKierowcyDao);
        registerDao(StawkiPasazera.class, stawkiPasazeraDao);
        registerDao(Trasa.class, trasaDao);
    }
    
    public void clear() {
        stawkiKierowcyDaoConfig.getIdentityScope().clear();
        stawkiPasazeraDaoConfig.getIdentityScope().clear();
        trasaDaoConfig.getIdentityScope().clear();
    }

    public StawkiKierowcyDao getStawkiKierowcyDao() {
        return stawkiKierowcyDao;
    }

    public StawkiPasazeraDao getStawkiPasazeraDao() {
        return stawkiPasazeraDao;
    }

    public TrasaDao getTrasaDao() {
        return trasaDao;
    }

}
