package pl.kilometrowka.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STAWKI_PASAZERA.
 */
public class StawkiPasazera {

    private Long id;
    private Integer km_od;
    private Integer km_do;
    private Double cena;

    public StawkiPasazera() {
    }

    public StawkiPasazera(Long id) {
        this.id = id;
    }

    public StawkiPasazera(Long id, Integer km_od, Integer km_do, Double cena) {
        this.id = id;
        this.km_od = km_od;
        this.km_do = km_do;
        this.cena = cena;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getKm_od() {
        return km_od;
    }

    public void setKm_od(Integer km_od) {
        this.km_od = km_od;
    }

    public Integer getKm_do() {
        return km_do;
    }

    public void setKm_do(Integer km_do) {
        this.km_do = km_do;
    }

    public Double getCena() {
        return cena;
    }

    public void setCena(Double cena) {
        this.cena = cena;
    }

}
