package pl.kilometrowka.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import pl.kilometrowka.dao.StawkiPasazera;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STAWKI_PASAZERA.
*/
public class StawkiPasazeraDao extends AbstractDao<StawkiPasazera, Long> {

    public static final String TABLENAME = "STAWKI_PASAZERA";

    /**
     * Properties of entity StawkiPasazera.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Km_od = new Property(1, Integer.class, "km_od", false, "KM_OD");
        public final static Property Km_do = new Property(2, Integer.class, "km_do", false, "KM_DO");
        public final static Property Cena = new Property(3, Double.class, "cena", false, "CENA");
    };


    public StawkiPasazeraDao(DaoConfig config) {
        super(config);
    }
    
    public StawkiPasazeraDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STAWKI_PASAZERA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KM_OD' INTEGER," + // 1: km_od
                "'KM_DO' INTEGER," + // 2: km_do
                "'CENA' REAL);"); // 3: cena
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STAWKI_PASAZERA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StawkiPasazera entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer km_od = entity.getKm_od();
        if (km_od != null) {
            stmt.bindLong(2, km_od);
        }
 
        Integer km_do = entity.getKm_do();
        if (km_do != null) {
            stmt.bindLong(3, km_do);
        }
 
        Double cena = entity.getCena();
        if (cena != null) {
            stmt.bindDouble(4, cena);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StawkiPasazera readEntity(Cursor cursor, int offset) {
        StawkiPasazera entity = new StawkiPasazera( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // km_od
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // km_do
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3) // cena
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StawkiPasazera entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKm_od(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setKm_do(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCena(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StawkiPasazera entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StawkiPasazera entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
