package pl.kilometrowka.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import pl.kilometrowka.dao.StawkiKierowcy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STAWKI_KIEROWCY.
*/
public class StawkiKierowcyDao extends AbstractDao<StawkiKierowcy, Long> {

    public static final String TABLENAME = "STAWKI_KIEROWCY";

    /**
     * Properties of entity StawkiKierowcy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Km = new Property(1, Integer.class, "km", false, "KM");
        public final static Property Cena = new Property(2, Double.class, "cena", false, "CENA");
    };


    public StawkiKierowcyDao(DaoConfig config) {
        super(config);
    }
    
    public StawkiKierowcyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STAWKI_KIEROWCY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KM' INTEGER," + // 1: km
                "'CENA' REAL);"); // 2: cena
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STAWKI_KIEROWCY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StawkiKierowcy entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer km = entity.getKm();
        if (km != null) {
            stmt.bindLong(2, km);
        }
 
        Double cena = entity.getCena();
        if (cena != null) {
            stmt.bindDouble(3, cena);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StawkiKierowcy readEntity(Cursor cursor, int offset) {
        StawkiKierowcy entity = new StawkiKierowcy( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // km
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2) // cena
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StawkiKierowcy entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKm(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCena(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StawkiKierowcy entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StawkiKierowcy entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
