package pl.kilometrowka.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STAWKI_PASAZERA.
 */
public class StawkiPasazera {

    private Long id;
    private Integer km;
    private Double cena;

    public StawkiPasazera() {
    }

    public StawkiPasazera(Long id) {
        this.id = id;
    }

    public StawkiPasazera(Long id, Integer km, Double cena) {
        this.id = id;
        this.km = km;
        this.cena = cena;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getKm() {
        return km;
    }

    public void setKm(Integer km) {
        this.km = km;
    }

    public Double getCena() {
        return cena;
    }

    public void setCena(Double cena) {
        this.cena = cena;
    }

}
