package pl.kilometrowka.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRASA.
 */
public class Trasa {

    private Long id;
    private String miasta;
    private Integer km;
    private Boolean kierowca;
    private Boolean autoSluzbowe;
    private Boolean czyZPasazerem;
    private java.util.Date data;

    public Trasa() {
    }

    public Trasa(Long id) {
        this.id = id;
    }

    public Trasa(Long id, String miasta, Integer km, Boolean kierowca, Boolean autoSluzbowe, Boolean czyZPasazerem, java.util.Date data) {
        this.id = id;
        this.miasta = miasta;
        this.km = km;
        this.kierowca = kierowca;
        this.autoSluzbowe = autoSluzbowe;
        this.czyZPasazerem = czyZPasazerem;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMiasta() {
        return miasta;
    }

    public void setMiasta(String miasta) {
        this.miasta = miasta;
    }

    public Integer getKm() {
        return km;
    }

    public void setKm(Integer km) {
        this.km = km;
    }

    public Boolean getKierowca() {
        return kierowca;
    }

    public void setKierowca(Boolean kierowca) {
        this.kierowca = kierowca;
    }

    public Boolean getAutoSluzbowe() {
        return autoSluzbowe;
    }

    public void setAutoSluzbowe(Boolean autoSluzbowe) {
        this.autoSluzbowe = autoSluzbowe;
    }

    public Boolean getCzyZPasazerem() {
        return czyZPasazerem;
    }

    public void setCzyZPasazerem(Boolean czyZPasazerem) {
        this.czyZPasazerem = czyZPasazerem;
    }

    public java.util.Date getData() {
        return data;
    }

    public void setData(java.util.Date data) {
        this.data = data;
    }

}
